name: build_ErfanGSIs

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
env:
  ROM_URL: https://roms.cirrus-ci.workers.dev/0:/rosy/ArcaneOS_rosy-EXORT-UNOFFICIAL-20211028-0354.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Jakarta
  ZIP: ArcaneOS_rosy-EXORT-UNOFFICIAL-20211028-0354

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - uses: fastai/workflows/ssh@master
         with:
           ssh_key: ${{ secrets.SSH_KEY }}
           key_file: id_ecdsa
       - uses: actions/checkout@v2
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/AnGgIt88/ErfanGSIs-VelanGSIs ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ./ErfanGSIs/url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs/output
             mkdir final
             zip -r final/$ZIP.zip ./*
       
       - name: Upload SGSI to action-gh-release...
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: $GITHUB_WORKSPACE/ErfanGSIs/output/final/*
           name: ArcaneOS_rosy-EXORT-UNOFFICIAL-20211028-0354
           tag: ArcaneOS_rosy-EXORT-UNOFFICIAL-20211028-0354-${{ github.run_number }}
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: Session Setup
           uses: mxschmitt/action-tmate@master
         
            
